services:
  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    image: playerinlife/app:latest
    restart: unless-stopped
    env_file: .env
    networks: [appnet]
    depends_on:
      - mariadb
      - redis

  reverb:
    image: playerinlife/app:latest
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    restart: unless-stopped
    env_file: .env
    networks: [appnet]
    depends_on:
      - redis
      - mariadb

  queue:
    image: playerinlife/app:latest
    command: php artisan queue:work --sleep=3 --tries=3
    restart: unless-stopped
    env_file: .env
    networks: [appnet]
    depends_on:
      - redis

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks: [appnet]

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks: [appnet]

  turn:
    image: instrumentisto/coturn
    restart: unless-stopped
    ports:
      - '3478:3478'
      - '3478:3478/udp'
      - '49160-49200:49160-49200/udp'
    environment:
      TURN_REALM: call1x1.playerinlife.ru
      TURN_USER: turnuser
      TURN_PASSWORD: strongpassword
    networks: [appnet]

  # caddy:
  #   image: playerinlife/app:latest
  #   # env_file: .env
  #   command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #     - '443:443/udp'
  #   volumes:
  #     - ./docker/prod/Caddyfile:/etc/caddy/Caddyfile:ro
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   networks: [appnet]
  #   depends_on:
  #     - app
  #     - reverb

networks:
  appnet:

volumes:
  mariadb_data:
  redis_data:
  caddy_data:
  caddy_config:
