log_level: info
port: 7880

redis:
  address: redis:6379

rtc:
  turn_servers:
    - urls:
        - turn:call.playerinlife.ru:3478?transport=udp
        - turn:call.playerinlife.ru:3478?transport=tcp
      username: turnuser
      password: turnpass
